### PR TITLE
Docker file added

### PR DESCRIPTION
**Pull request by gagandeepp**
### Brief Summary of Changes
Add Docker file for the cloudinary-cli
Closes: https://github.com/cloudinary/cloudinary-cli/issues/25

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

### CODE REVIEW

**Comment by gagandeepp** [comment]
@laurenskling @const-cloudinary  Please review the MR

**Comment by const-cloudinary** [comment]
@gagandeepp please see: https://github.com/cloudinary/cloudinary-cli/issues/25#issuecomment-2410280241

**Review by const-cloudinary — CHANGES_REQUESTED** [review]
@gagandeepp Please see https://github.com/cloudinary/cloudinary-cli/issues/25#issuecomment-2410280241

**Review by const-cloudinary — APPROVED** [review]

**Comment by gagandeepp** [comment]
@const-cloudinary can you please add Hacktoberfest label to this?

**Comment by const-cloudinary** [comment]
@gagandeepp Thank you for contribution!

**Comment by const-cloudinary** [comment]
> @const-cloudinary can you please add Hacktoberfest label to this?

I think it should be automatically counted, but I'll check.

**Comment by colbyfayock** [comment]
@gagandeepp the label is added to the repository level, its not necessary to add to the issue

thanks for your contribution. this PR is eligible for free Cloudinary Hackatoberfest swag. Please send me an email at [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your name, GitHub username, and a link to the PR where I'll send further instructions.

Happy Hacktoberfest!

**Pull request merged**
