### PR TITLE
MYPY Types added

### PR DESCRIPTION
**Pull request by gagandeepp**
### Brief Summary of Changes
Fixes: https://github.com/cloudinary/pycloudinary/issues/377

#### What does this PR address?
- [x] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [ ] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

Before :
image

After: Old screenshot currently on 18 errors are there
image

### CODE REVIEW

**Comment by gagandeepp** [comment]
@const-cloudinary  Does the initial changes looks good?

**Comment by gagandeepp** [comment]
> @const-cloudinary Does the initial changes looks good?

Once you gives go ahead, I will implement the rest of the stubs and also add a precommit hook in the repository

**Comment by const-cloudinary** [comment]
@gagandeepp , yeah looks great, please go ahead!

**Comment by gagandeepp** [comment]
> Current Status: image

@const-cloudinary  current status ^^^

**Comment by const-cloudinary** [comment]
@gagandeepp , this is what I see:

Screenshot 2024-10-16 at 19 44 17

**Comment by gagandeepp** [comment]
> @gagandeepp , this is what I see:
> 
> Screenshot 2024-10-16 at 19 44 17

Screenshot 2024-10-16 204200

**Comment by gagandeepp** [comment]
@const-cloudinary Latest status:
image

**Comment by gagandeepp** [comment]
@const-cloudinary Can you please take a look at this?

**Review by const-cloudinary — COMMENTED** [review]
@gagandeepp , Thank you for your PR!

This looks like a huge overhead of supporting such files, like, for every new option that is added, it needs to be added twice.

For example duplication of all `@command` definitions, `FORMAT_ALIASES`, `not_callable`.

Isn't it better to combine `pyi` and `py` files into one?

If no, is there any sort of automation? Like GitHub action? To make sure we don't forget to update `pyi` files ?

**Comment by gagandeepp** [comment]
> @gagandeepp , Thank you for your PR!
> 
> This looks like a huge overhead of supporting such files, like, for every new option that is added, it needs to be added twice.
> 
> For example duplication of all `@command` definitions, `FORMAT_ALIASES`, `not_callable`.
> 
> Isn't it better to combine `pyi` and `py` files into one?
> 
> If no, is there any sort of automation? Like GitHub action? To make sure we don't forget to update `pyi` files ?

Let me take a look of

**Pull request closed without merging**
